kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: local
spec:
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.persistence.mountPath | quote }}
